# -*- coding: utf-8 -*-
"""18.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiVJePKfJO5qZKvQuw0Nede0C7fwm0sT
"""

def check_number(num):
    if num > 0:
        print("The number is positive")
    elif num < 0:
        print("The number is negative")
    else:
        print("The number is zero")

num = int(input("Enter a number: "))
check_number(num)