# -*- coding: utf-8 -*-
"""18.3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lfdv1Seb_MSUOpISkK4SULe8WBPdVu2P
"""

def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n - 1)

if __name__ == "__main__":
    n = int(input().strip())
    print(f"Factorial = {factorial(n)}")