# -*- coding: utf-8 -*-
"""18.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jdii176Gloh6NVf0dR9rnaWgyKLZYu5J
"""

def print_students(students):
    print("Student List:")
    for name in students:
        print(name)

students = ["Alice", "Bob", "Charlie"]
print_students(students)